### ISSUE TITLE
Ground truth annotations

### ISSUE THREAD

**Issue by Ellyuca** [annonymousiccv/uni-nlx#1]
Hi. I hope you are doing well!
First of all, thanks for this great work.

Secondly, I was looking at the repo & code but I couldn't find the ground truth annotations files ( I might have missed something).
Could you share the ground truth annotation files?

Thank you for your help and looking forward to hearing from you 😃.
Best wishes.

**Comment by fawazsammani** [comment]
Hi @Ellyuca ,
Thanks for your interest in our work.
I have uploaded them already. Check the readme file, under the Data subsection.

Regards
Fawaz

**Comment by Ellyuca** [comment]
Hi @fawazsammani,
Thank you!
