### ISSUE TITLE
code for analysis in appendix

### ISSUE THREAD

**Issue by bakachan19** [annonymousiccv/uni-nlx#2]
Hi. 
I was wondering if you could share the code for the analysis presented in the appendix of the paper.
I am interested in producing the attention maps like in Figure 5:
 
> In Figure 5, we visualize the attention maps for the generated answers from  the last layer of the model.

and the explanations conditioned on the class as discussed here:

> In zero-shot transfer, we assume that the class categories  are readily available. We utilize NLX-GPT trained on ImageNetX to generate an explanation for a class we condition on. The process involves providing our distilled GPT-2 model with the prompt ”the answer is {class label} because” and subsequently obtaining the generated explanation.

Thanks.
Best regards.

**Comment by fawazsammani** [comment]
Hi @bakachan19 
Thanks for your interest in our work. 

You may find the conditioned explanations here (we average over 4 different images, see Table 4): 
[database.json](https://github.com/fawazsammani/uni-nlx/files/14037042/database.json)
[database_1.json](https://github.com/fawazsammani/uni-nlx/files/14037043/database_1.json)
[database_2.json](https://github.com/fawazsammani/uni-nlx/files/14037044/database_2.json)
[database_3.json](https://github.com/fawazsammani/uni-nlx/files/14037045/database_3.json)

The code to visualize the attention is [here](https://drive.google.com/file/d/12-YwIVbd_XFQYpAyPU5G-motxjv8Gx9H/view?usp=sharing). It is basically very similar to the ones [here](https://huggingface.co/spaces/Fawaz/nlx-gpt/blob/main/app.py) and [here](https://huggingface.co/spaces/Fawaz/nlx_gpt_action/blob/main/app.py). 

Regards

**Comment by bakachan19** [comment]
Thank you!
